### ISSUE TITLE
Add a tap for Homebrew

### ISSUE THREAD

**Issue by Legonois** [kddresearch/devcontainers-feature#7]
Add the Homebrew-Package feature, and add a tap option.

## Milestones
- [x] Add the Homebrew-Package to the current repo
- [x] Add a area for the tap option
- [x] Have the script add the tap before the installation
- [x] Add the tests
